### PR TITLE
Added Enzyme test for pattern form

### PR DESCRIPTION
**Pull request by NetkachovaAnastasiya**
## Description

Created Enzyme test for pattern-form. Testing rendering components, Redux, Formik, propTypes and LoadingBar.

### Checklist
- [x] 🔽 My branch is up-to-date with "development" branch
- [x] ✅ All tests passed locally
- [x] ✨ My changes working with up-to-date front-end and back-end part locally, like charm
- [x] 🔗 https://github.com/ita-social-projects/horondi_admin/issues/450

### CODE REVIEW

**Comment by AndriyLymych** [comment]
Screenshot 2021-06-18 at 20 07 12
the coverage should be more then 80%

**Comment by AndriyLymych** [comment]
Screenshot 2021-06-18 at 20 07 29
please, link your task

**Comment by AndriyLymych** [comment]
Screenshot 2021-06-18 at 20 09 35
remove all commented  text lines

**Comment by sergklukvin** [comment]
Без імені
Should avoid console.error and console.warn
Coverage should be at least 80%

**Comment by sergklukvin** [comment]
Add project here

**Review by grebiniuk — CHANGES_REQUESTED** [review]
Please add a coverage screenshot in the description.
It looks like the coverage now is less than 80%
Which is unacceptable.

**Pull request closed without merging**
