### PR TITLE
[Cтворити гобелен] Error messages that mandatory fields are filled in with to long values is not shown Fixbug/795

### PR DESCRIPTION
**Pull request by ostgit12**
## Description
fixing bug field validation message, such as: when we input into 'name' or 'description' less than 2 charachters validation message is shown and when we input into 'name' more than 50 charachters or input into 'description' more than 1000 characters validation message is shown.

#### Screenshots
Original screenshot
image

Updated screenshot
image

### Checklist
- [+] 🔽 My branch is up-to-date with "development" branch
- [+] ✅ All tests passed locally
- [+] ✨ My changes working with up-to-date front-end and back-end part locally, like charm
- [+] 🔗 Link pull request to issue

### CODE REVIEW

**Review by Elugormo — CHANGES_REQUESTED** [review]
Validation doesn't work. Change your validation message appear on onBlur
Please git pull from development by using "git pull origin development".

**Review by grebiniuk — CHANGES_REQUESTED** [review]
Please fix comments

**Comment by grebiniuk** [comment]
@ostgit12 Why did you remove these two files?

**Review by sergklukvin — DISMISSED** [review]
image
It dosn't work

**Review by Vlodkojr — COMMENTED** [review]
errr

**Review by halaburdataras — APPROVED** [review]

**Review by Vlodkojr — APPROVED** [review]

**Pull request merged**
