### PR TITLE
Refactoring components on Admin pannel #674

### LINKED ISSUE #674: (SP:3)Refactoring component on Admin pannel
Problem: 

- Every component, every form uses different components. They are not unified.
- Back/Save/... buttons
- ImageUpload
- Behaviour
- Styles
- Etc.

including:
https://github.com/ita-social-projects/horondi_admin/issues/672

### PR DESCRIPTION
**Pull request by Walleriy**
Add padding in mainPage->slider,  forms/contacts-form
move buttons down in news
add padding and delete general paper in business-page-form
fixes #674 

1) Add padding in forms/contacts-form

#### Screenshots

Original             |  Updated
:-------------------------:|:-------------------------:
image | image

2) Add padding in mainPage->slider

#### Screenshots

Original             |  Updated
:-------------------------:|:-------------------------:
image | image

3) Add padding and delete general paper in business-page-form

#### Screenshots

Original             |  Updated
:-------------------------:|:-------------------------:
image | image

### Checklist
- [x] 🔽 My branch is up-to-date with "development" branch
- [x] ✅ All tests passed locally
- [x] ✨ My changes working with up-to-date front-end and back-end part locally, like charm
- [x] 🔗 Link pull request to issue

### CODE REVIEW

**Comment by IlyaBelik** [comment]
fix codesmelss 
image

**Comment by Walleriy** [comment]
> fix codesmelss
> image

Done

**Review by IlyaBelik — APPROVED** [review]

**Review by grebiniuk — CHANGES_REQUESTED** [review]
Please revert all your changes for news-form.
Nav buttons like Cancel and Save will be position fixed at the top for all the forms.

Thanks!

**Comment by Walleriy** [comment]
> Please revert all your changes for news-form.
> Nav buttons like Cancel and Save will be position fixed at the top for all the forms.
> 
> Thanks!

Done!

**Review by grebiniuk — APPROVED** [review]

**Review by IlyaBelik — APPROVED** [review]

**Pull request merged**
