### PR TITLE
Eslintrc fix

### PR DESCRIPTION
**Pull request by Meamzy**
Installed a plugin eslint-config-prettier 
To work with fix, local env needs the 'npm install' command.

### Checklist
- [x] 🔽 My branch is up-to-date with "development" branch
- [x] ✅ All tests passed locally
- [x] ✨ My changes working with up-to-date front-end and back-end part locally, like charm
- [x] 🔗 Link pull request to issue

### CODE REVIEW

**Review by mvmoshchovskyi — APPROVED** [review]

**Comment by sergklukvin** [comment]
Без імені

Why package-lock.json was removed?

**Comment by sergklukvin** [comment]
Pre-commit is different from front-end.

**Review by sergklukvin — CHANGES_REQUESTED** [review]
Pre-commit is different from front-end.

**Review by sergklukvin — CHANGES_REQUESTED** [review]
Без імені

Why package-lock.json has been changed?

**Pull request merged**
