### PR TITLE
Add sizes to Databse

### PR DESCRIPTION
**Pull request by NikitaDenysenko**
added ui form for accepting and dispatching sizes to database
Знімок екрана 2021-01-27 о 18 22 04

Знімок екрана 2021-01-27 о 18 22 11

### CODE REVIEW

**Comment by moran711** [comment]
If I add this size I wanna to see some hint's that I set invalid data and disabled add size button when I don't fill all inputs. 
image

**Comment by moran711** [comment]
I think that it would be better to show snackbar if I will got some errors in response
image

**Comment by moran711** [comment]
I think it would be better to add possibility to remove/update size

**Comment by moran711** [comment]
Please remove this console.logs 
image

**Comment by moran711** [comment]
If I add size i don't have possibility to add model
image

**Comment by kapoliub** [comment]
Screen Shot 2021-01-27 at 19 08 00
fix button position (margin)

**Comment by kapoliub** [comment]
Screen Shot 2021-01-27 at 19 08 09
change title as header

**Comment by kapoliub** [comment]
Screen Shot 2021-01-27 at 19 08 50
- we havn't buttons position like this. replace buttons together in the left corner due our mocks
- make saveButton disabled when input field are empty.

**Comment by kapoliub** [comment]
Screen Shot 2021-01-27 at 19 08 56
fix position of this checkbox

**Pull request closed without merging**
